# Generated by Django 2.1.3 on 2018-12-02 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_layer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('max_guests', models.PositiveIntegerField(blank=True, null=True)),
                ('display_address', models.TextField()),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('approx_display_address', models.TextField()),
                ('approx_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('approx_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('protect_real_address', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_layer.User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
