# Generated by Django 2.1.7 on 2019-03-17 18:57

import django.db.models.deletion
from django.db import migrations, models

import db_layer.invitations.models.invitation_code


class Migration(migrations.Migration):

    dependencies = [
        ('db_layer', '0005_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationCode',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('invitation_code', models.CharField(default=db_layer.invitations.models.invitation_code.generate_invitation_code, editable=False, max_length=127, primary_key=True, serialize=False)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_layer.Trip')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
